= Pytest Plugin - _Rerun Failures based On Report Portal_

The `pytest_plugins/rerun_rp/reren_rp.py` module is designed as a plugin to pytest in the robottelo test framework.

This plugin helps https://github.com/SatelliteQE[SatelliteQE] to rerun `failed or skipped` and specific `user` tests from the given finished ReportPortal launch.

== Goal:

This plugin is to rerun failed or skipped tests to retest flaky and fixed tests everyday on CI. QEs can also use this plugin for `test failure analysis` by locally rerunning their failed or skipped tests.

== Checks:

Checks that will skip the rerun:

** Skip rerun execution for wrong arguments to `--only-failed` option.
** Skip rerun execution if the launch for the Report Portal is still processing.
** Skip rerun execution if the failed tests percentage in the latest finished launch is more than the `fail_threshold` percent set in robottelo properties. If it is not set, the fail_threshold is 20% by default.


== Usage:

* To rerun all failed or skipped tests

[source,bash]
----
$ py.test --only-failed    ## To rerun all skipped tests
$ py.test --only-skipped   ## To rerun all skipped tests
$ py.test --only-failed to_investigate      ## To rerun all failed tests with defect status
$ py.test --only-failed to_investigate,automation_bug       ## To rerun all failed tests with multiple defect status
$ py.test --user jyejare   ## To rerun user specific tests
$ py.test --user jyejare --only-skipped     ## To rerun user specific failed or skipped tests
----


== Example:

* To rerun `failed` tests with `defect_type` = _to_investigate_ for `user` _jyejare_ from `tests/foreman/api/test_computeresource_azure.py`
____
 Observe only 1 test is selected
____

[source,shell]
----
$ pytest tests/foreman/api/test_computeresource_azurerm.py --collect-only --rp-reference-launch-uuid bd4bc4ba-1d6f-465e-87d8-086c0b6352d5 --user jyejare --only-failed
================ test session starts =================
platform darwin -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /Users/jitendrayejare/JWorkspace/GitRepos/robottelo, configfile: pyproject.toml
plugins: xdist-2.5.0, forked-1.4.0, reportportal-5.1.1, mock-3.7.0, services-2.2.1, ibutsu-2.0.2, cov-3.0.0
collected 11 items / 10 deselected / 1 selected

<Package api>
  <Module test_computeresource_azurerm.py>
    <Class TestAzureRMHostProvisioningTestCase>
      <Function test_positive_azurerm_host_power_on_off>

======== 1/11 tests collected (10 deselected) in 27.92s ========
----
