= Pytest Plugin - _Rerun Failures based On Report Portal_

The `pytest_plugins/rerun_rp/reren_rp.py` module is designed as a plugin to the pytest in robottelo test framework.

This plugin helps https://github.com/SatelliteQE[SatelliteQE] to rerun `failed or skipped` and `user specific` tests from latest finished ReportPortal launch.

*Checks, those will skip the rerun:*

** Skip rerun execution if the options are wrong to `--only-failed`
** Skip rerun execution if the latest launch for the report portal is still processing.
** Skip rerun execution if the fail percentage of the latest complete launch is more than `fail_threshold` set in robottelo properties. If its not set there the fail_threshold is 20% by default.
   The `pass percent` is calculated as `100*(passed/executed)`.


== Usage:

* To re-run all failed or skipped tests

[source,bash]
----
py.test --only-failed
----

- OR -

[source,bash]
----
py.test --only-skipped
----


* To re-run all failed tests with defect status `e.g to_investigate`

[source,bash]
----
py.test --only-failed to_investigate
----

* To re-run all failed tests with multiple defect statuses `e.g to_investigate, automation_bug etc`

[source,bash]
----
py.test --only-failed to_investigate,automation_bug
----

* To re-run user specific tests

[source,bash]
----
py.test --user jyejare
----

* One can also re-run user specific failed / skipped tests
e.g:

[source,bash]
----
py.test --user jyejare --only-skipped
----

==== Re-run Example:

* To Re-run `yet to investigate` failed tests of user jyejare from `tests/foreman/ui/test_ldap_authentication.py`
____
 Observe only 2 tests are selected
____

[source,shell]
----
$ py.test --collect-only tests/foreman/ui/test_ldap_authentication.py --only-failed to_investigate --user jyejare
======= test session starts ========

2020-10-30 16:58:01 - robottelo.rerun_failures.uncollector - DEBUG - Selecting/Deselecting tests based on latest launch test results..
2020-10-30 16:58:01 - robottelo.rerun_failures.uncollector - DEBUG - Selected 2 and deselected 17 tests based on latest launch test results.
2020-10-30 11:28:01 - conftest - DEBUG - Collected 2 test cases
2020-10-30 16:58:01 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 21 items / 19 deselected / 2 Selected
<Package /home/jitendrayejare/Desktop/RedHat/RoboTelloNew/robottelo/tests/foreman/ui>
  <Module test_ldap_authentication.py>
    <Function test_single_sign_on_ldap_ipa_server>
    <Function test_single_sign_on_using_rhsso>

======== 19 deselected in 11.59 seconds ========
----
