= Pytest Plugin - _Rerun Failures based On Report Portal_

The `pytest_plugins/rerun_rp/reren_rp.py` module is designed as a plugin to pytest in the robottelo test framework.

This plugin helps https://github.com/SatelliteQE[SatelliteQE] to rerun `failed or skipped` and specific `user` tests from the latest finished ReportPortal launch.

== Goal:

This plugin is to rerun failed or skipped tests to retest flaky and fixed tests everyday on CI. QEs can also use this plugin for `test failure analysis` by locally rerunning their failed or skipped tests.

== Checks:

Checks that will skip the rerun:

** Skip rerun execution for wrong arguments to `--only-failed` option.
** Skip rerun execution if the latest launch for the Report Portal is still processing.
** Skip rerun execution if the failed tests percentage in the latest finished launch is more than the `fail_threshold` percent set in robottelo properties. If it is not set, the fail_threshold is 20% by default.


== Usage:

* To rerun all failed or skipped tests

[source,bash]
----
$ py.test --only-failed    ## To rerun all skipped tests
$ py.test --only-skipped   ## To rerun all skipped tests
$ py.test --only-failed to_investigate      ## To rerun all failed tests with defect status
$ py.test --only-failed to_investigate,automation_bug       ## To rerun all failed tests with multiple defect status
$ py.test --user jyejare   ## To rerun user specific tests
$ py.test --user jyejare --only-skipped     ## To rerun user specific failed or skipped tests
----


== Example:

* To rerun `failed` tests with `defect_type` _automation_bug_ of `user` _jyejare_ from `tests/foreman/ui/test_ldap_authentication.py`
____
 Observe only 2 tests are selected
____

[source,shell]
----
$ py.test --collect-only tests/foreman/ui/test_ldap_authentication.py --only-failed automation_bug --user jyejare
======= test session starts ========

2020-10-30 16:58:01 - robottelo.rerun_failures.uncollector - DEBUG - Selecting/Deselecting tests based on latest launch test results..
2020-10-30 16:58:01 - robottelo.rerun_failures.uncollector - DEBUG - Selected 2 and deselected 17 tests based on latest launch test results.
2020-10-30 11:28:01 - conftest - DEBUG - Collected 2 test cases
2020-10-30 16:58:01 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 21 items / 19 deselected / 2 Selected
<Package /home/jitendrayejare/Desktop/RedHat/RoboTelloNew/robottelo/tests/foreman/ui>
  <Module test_ldap_authentication.py>
    <Function test_single_sign_on_ldap_ipa_server>
    <Function test_single_sign_on_using_rhsso>

======== 19 deselected in 11.59 seconds ========
----
