broker: "tests/foreman/ -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'"
deepdiff: "tests/foreman/endtoend/test_api_endtoend.py -k 'test_positive_get_links'"
dynaconf: "tests/foreman/api/test_ldapauthsource.py -k 'test_positive_endtoend'"
manifester: "tests/foreman/cli/test_contentview.py -k 'test_positive_promote_rh_content'"
navmazing: "tests/foreman/ui/test_repository.py -k 'test_positive_create_as_non_admin_user'"
pyotp: "tests/foreman/ui/test_ldap_authentication.py -k 'test_positive_login_user_password_otp'"
pytest-xdist: "tests/foreman/ -n 3 -m 'build_sanity'"
pytest: "tests/foreman/ -m 'build_sanity'"
python-box: "tests/foreman/cli/test_webhook.py -k 'test_positive_end_to_end'"
requests: "tests/foreman/cli/test_repository.py -k 'test_file_repo_contains_only_newer_file'"
wait-for: "tests/foreman/api/test_reporttemplates.py -k 'test_positive_schedule_entitlements_report'"
wrapanapi: "tests/foreman/api/test_computeresource_gce.py::TestGCEHostProvisioningTestCase::test_positive_gce_host_provisioned[sat]"
