screenshots_path: /tmp/robottelo/screenshots/
locale: en_US.UTF-8
verbosity: debug
tmp_dir: /var/tmp
artifacts_server: server.example.com
log_driver_commands:
  - newSession
  - windowMaximize
  - get
  - findElement
  - sendKeysToElement
  - clickElement
  - mouseMoveTo
browser: selenium
webdriver: chrome
browseroptions:
webdriver_binary: /usr/bin/firefox
webdriver_desired_capabilities:
  platform: Linux
  browserName: chrome
  unhandledPromptBehavior: dismiss
  unexpectedAlertBehaviour: ignore
  acceptInsecureCerts: true
command_executor: http://127.0.0.1:4444/wd/hub
saucelabs_user:
saucelabs_key:
cdn: true
run_one_datapoint: false
rhel6_repo: http://example.com/yum/repo_files/rhel6-updates.repo
rhel7_repo: http://example.com/yum/repo_files/rhel7-updates.repo
rhel6_os: http://example.com/yum/rhel6-os/
rhel7_os: http://example.com/yum/rhel7-os/
rhel8_os:
  baseos: http://example.com/rhel-8/BaseOS/x86_64/os/
  appstream: http://example.com/rhel-8/AppStream/x86_64/os/
sattools_repo:
  rhel6: http://sattools/repo/el6
  rhel7: http://sattools/repo/el7
swid_tools_repo: https://example.com/swid-rhel-8.repo
capsule_repo:
